# Generated by Django 5.0.7 on 2024-12-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnify', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
