# Generated by Django 5.0.7 on 2024-12-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnify', '0007_remove_profile_bio_profile_city_or_town_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
